# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2031dc9fee5d14af0daf512ac58306afea5170b3b4229c3afb7db2c72711392520add47adc499f27fa2c5b89d945e34a4852b69cfe0060cc654e408926fe21

test:
  secret_key_base: 7116ffc322e7e582d676e3c9cd207420dab9ed2d57000d6d63ddae6ef33fd57bd71c45d3ad9bd1443af566c6750a5819d358c730d7dc8430fde969e8a608695f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
